//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_message.cpp
//  Source: dds_message.idl
//  Generated: Wed Aug  5 20:37:35 2015
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ros/dds_message.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Octet, struct OctSeq_uniq_>;
#endif



