module ROSDDS
{
   typedef sequence<octet> OctSeq;

   struct Msg
   {
      unsigned long version;
      string callerId;
      octet reserved[8];
      OctSeq message;
   };
   #pragma keylist Msg
};
