//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_message.cpp
//  Source: dds_message.idl
//  Generated: Sun Aug 24 02:45:11 2014
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ros/dds_message.h"


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_FArray_var< ROSDDS::Msg::_reserved, ROSDDS::Msg::_reserved_slice, struct ROSDDS::Msg::_reserved_uniq_>;
template class DDS_DCPS_Array_forany< ROSDDS::Msg::_reserved, ROSDDS::Msg::_reserved_slice, struct ROSDDS::Msg::_reserved_uniq_>;
#endif

template <>
ROSDDS::Msg::_reserved_slice* DDS_DCPS_ArrayHelper < ROSDDS::Msg::_reserved, ROSDDS::Msg::_reserved_slice, ROSDDS::Msg::_reserved_uniq_>::alloc ()
{
   return ROSDDS::Msg::_reserved_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < ROSDDS::Msg::_reserved, ROSDDS::Msg::_reserved_slice, ROSDDS::Msg::_reserved_uniq_>::copy (ROSDDS::Msg::_reserved_slice *to, const ROSDDS::Msg::_reserved_slice* from)
{
   ROSDDS::Msg::_reserved_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < ROSDDS::Msg::_reserved, ROSDDS::Msg::_reserved_slice, ROSDDS::Msg::_reserved_uniq_>::free (ROSDDS::Msg::_reserved_slice *ptr)
{
   ROSDDS::Msg::_reserved_free (ptr);
}

ROSDDS::Msg::_reserved_slice * ROSDDS::Msg::_reserved_alloc ()
{
   DDS::Octet * ret = (DDS::Octet*) new DDS::Octet [8];
   return (_reserved_slice *) ret;
}

void ROSDDS::Msg::_reserved_free (_reserved_slice * s)
{
   delete [] s;
}

void ROSDDS::Msg::_reserved_copy
(
   _reserved_slice * to,
   const _reserved_slice * from
)
{
   const DDS::Octet* sv = ( const DDS::Octet*) from;
   DDS::Octet* tv = (DDS::Octet*) to;
   for (DDS::ULong i = 0; i < 8; i++) tv[i] = sv[i];
}

ROSDDS::Msg::_reserved_slice * ROSDDS::Msg::_reserved_dup
   (const _reserved_slice * from)
{
   _reserved_slice * to = _reserved_alloc ();
   _reserved_copy (to, from);
   return to;
}

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Octet, struct OctSeq_uniq_>;
#endif



