// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_DDSTYPESUPPORTC_7ASTF9_H_
#define _TAO_IDL_DDSTYPESUPPORTC_7ASTF9_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "ddsC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace ROSDDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< ROSDDS::Msg, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> MsgSeq;
  

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_MsgSeq;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ROSDDS_MSGTYPESUPPORT__VAR_OUT_CH_)
#define _ROSDDS_MSGTYPESUPPORT__VAR_OUT_CH_

  class MsgTypeSupport;
  typedef MsgTypeSupport *MsgTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        MsgTypeSupport
      >
    MsgTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        MsgTypeSupport
      >
    MsgTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MsgTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MsgTypeSupport_ptr _ptr_type;
    typedef MsgTypeSupport_var _var_type;
    typedef MsgTypeSupport_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static MsgTypeSupport_ptr _duplicate (MsgTypeSupport_ptr obj);

    static void _tao_release (MsgTypeSupport_ptr obj);

    static MsgTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static MsgTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MsgTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MsgTypeSupport (void);

    

    virtual ~MsgTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MsgTypeSupport (const MsgTypeSupport &);

    void operator= (const MsgTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_MsgTypeSupport;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ROSDDS_MSGDATAWRITER__VAR_OUT_CH_)
#define _ROSDDS_MSGDATAWRITER__VAR_OUT_CH_

  class MsgDataWriter;
  typedef MsgDataWriter *MsgDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        MsgDataWriter
      >
    MsgDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        MsgDataWriter
      >
    MsgDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MsgDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MsgDataWriter_ptr _ptr_type;
    typedef MsgDataWriter_var _var_type;
    typedef MsgDataWriter_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static MsgDataWriter_ptr _duplicate (MsgDataWriter_ptr obj);

    static void _tao_release (MsgDataWriter_ptr obj);

    static MsgDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static MsgDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MsgDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::ROSDDS::Msg & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::ROSDDS::Msg & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::ROSDDS::Msg & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::ROSDDS::Msg & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::ROSDDS::Msg & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::ROSDDS::Msg & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::ROSDDS::Msg & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::ROSDDS::Msg & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::ROSDDS::Msg & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::ROSDDS::Msg & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MsgDataWriter (void);

    

    virtual ~MsgDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MsgDataWriter (const MsgDataWriter &);

    void operator= (const MsgDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_MsgDataWriter;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ROSDDS_MSGDATAREADER__VAR_OUT_CH_)
#define _ROSDDS_MSGDATAREADER__VAR_OUT_CH_

  class MsgDataReader;
  typedef MsgDataReader *MsgDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        MsgDataReader
      >
    MsgDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        MsgDataReader
      >
    MsgDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MsgDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MsgDataReader_ptr _ptr_type;
    typedef MsgDataReader_var _var_type;
    typedef MsgDataReader_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static MsgDataReader_ptr _duplicate (MsgDataReader_ptr obj);

    static void _tao_release (MsgDataReader_ptr obj);

    static MsgDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static MsgDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MsgDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::ROSDDS::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::ROSDDS::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::ROSDDS::MsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::ROSDDS::MsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::ROSDDS::Msg & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::ROSDDS::Msg & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::ROSDDS::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::ROSDDS::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::ROSDDS::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::ROSDDS::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::ROSDDS::MsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::ROSDDS::MsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::ROSDDS::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::ROSDDS::Msg & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::ROSDDS::Msg & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MsgDataReader (void);

    

    virtual ~MsgDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MsgDataReader (const MsgDataReader &);

    void operator= (const MsgDataReader &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_MsgDataReader;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module ROSDDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_ROSDDS_MSGTYPESUPPORT__TRAITS_)
#define _ROSDDS_MSGTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::ROSDDS::MsgTypeSupport>
  {
    static ::ROSDDS::MsgTypeSupport_ptr duplicate (
        ::ROSDDS::MsgTypeSupport_ptr p);
    static void release (
        ::ROSDDS::MsgTypeSupport_ptr p);
    static ::ROSDDS::MsgTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::ROSDDS::MsgTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ROSDDS_MSGDATAWRITER__TRAITS_)
#define _ROSDDS_MSGDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::ROSDDS::MsgDataWriter>
  {
    static ::ROSDDS::MsgDataWriter_ptr duplicate (
        ::ROSDDS::MsgDataWriter_ptr p);
    static void release (
        ::ROSDDS::MsgDataWriter_ptr p);
    static ::ROSDDS::MsgDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::ROSDDS::MsgDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ROSDDS_MSGDATAREADER__TRAITS_)
#define _ROSDDS_MSGDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::ROSDDS::MsgDataReader>
  {
    static ::ROSDDS::MsgDataReader_ptr duplicate (
        ::ROSDDS::MsgDataReader_ptr p);
    static void release (
        ::ROSDDS::MsgDataReader_ptr p);
    static ::ROSDDS::MsgDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::ROSDDS::MsgDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace ROSDDS
{
   void operator<<= ( ::CORBA::Any &, MsgTypeSupport_ptr); // copying
   void operator<<= ( ::CORBA::Any &, MsgTypeSupport_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, MsgTypeSupport_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, ROSDDS::MsgTypeSupport_ptr); // copying
 void operator<<= (::CORBA::Any &, ROSDDS::MsgTypeSupport_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ROSDDS::MsgTypeSupport_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace ROSDDS
{
   void operator<<= ( ::CORBA::Any &, MsgDataWriter_ptr); // copying
   void operator<<= ( ::CORBA::Any &, MsgDataWriter_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, MsgDataWriter_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, ROSDDS::MsgDataWriter_ptr); // copying
 void operator<<= (::CORBA::Any &, ROSDDS::MsgDataWriter_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ROSDDS::MsgDataWriter_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace ROSDDS
{
   void operator<<= ( ::CORBA::Any &, MsgDataReader_ptr); // copying
   void operator<<= ( ::CORBA::Any &, MsgDataReader_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, MsgDataReader_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, ROSDDS::MsgDataReader_ptr); // copying
 void operator<<= (::CORBA::Any &, ROSDDS::MsgDataReader_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ROSDDS::MsgDataReader_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
//#include "ros/ddsTypeSupportC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

